version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '5000:8080'
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    #volumes:
    # Mount local folder to container - change these paths as needed
    #- ./local-data:/app/data
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '4200:3000' # Changed from 80 to 3000
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
